owners = []
nickname = "cabotin"
username = "cabotin"
realname = "Abbot Cain"
server = "irc.libera.chat"
port = 6697
use_tls = true
encoding = "UTF-8"
channels = ["#contreloutre"]
ping_time = 180
ping_timeout = 20
burst_window_length = 8
max_messages_in_burst = 15
should_ghost = false

